### ISSUE TITLE
react-application-tenant-global-navbar stays open for pages on the same site

### ISSUE THREAD

**Issue by clohigh** [pnp/sp-dev-fx-extensions#201]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

I would want the nav menu to close after clicking a menu item link for a site page within the same site.

## Observed Behavior

So I was expecting the nav menu to close after clicking any item on the menu and navigating to the page. 

Yet if you click a nav item link that is in the same site the page loads but the nav menu stays open.

For example if I add this solution to contoso.sharepoint.com and add a link to a Site Page called Contoso Site Page.

Then when I click the link to the page contoso.sharepoint.com/sitepages/Contoso Site Page the page will load, yet the navigation menu is still open.

For whatever reason the page will load using something similar to Ajax and therefore not reload the entire site. 

## Submission Guidelines
@PaoloPia  @VesaJuvonen  @VelinGeorgiev 

## Steps to Reproduce

1. clone this repo
2.  in the command line run
3.  npm i
4.  open a modern site
5. go to the "Term Store Management" page of the site settings and create a new Term Set for the top NavBar 
6. Call the Term Sets with whatever name you like (for example,  I called my top NavBar Term Set 
 "MegaMenu ")
7. Configure the Term Sets for site managed navigation
8. Configure the navigation settings accordingly to your needs
9. Ensure that the TopMenuTermSet variable is set to the name of termset in this case MegaMenu
10. publish the solution on any hosting environment or CDN and update the cdnBasePath property in the write-manifests.json file with the base URL of your hosting environment
11. bundle and package the solution by executing the following commands in the command line:
12. gulp bundle --ship
13. gulp package-solution --ship
14. upload the content of the ./temp/deploy subfolder of the sample root folder into the target hosting environment
15. add to the "Apps for SharePoint" library of the AppCatalog in your tenant the spfx-tenant-global-navbar.sppkg file that you will find under the ./sharepoint/solution subfolder of the sample root folder
16. the sample is tenant-wide available, so you don't need to install it to every single target site, you simply need to bind the application customizer to the target site. In order to do that, you can use the PowerShell script TenantGlobalNavBarProvisionCustomizer.ps1
17. So if you need to add it to contoso.sharepoint.com update the  "Connect-PnPOnline "https://<your-tenant>.sharepoint.com/sites/<your-site>" -Credentials $credentials" line then run the PowerShell script
18.  The solution should then be available.

** I've noticed this behavior of all spfx react mega-menu and mega menus in general.

**Comment by maciejmaksymo** [comment]
Hello @clohigh ,

Did you by any chance manage to fix this on your own?
I have the very same problem and I'm looking for fixes or at least workarounds.

Best regards
Maciej

**Comment by jurivero** [comment]
Hi, @clohigh,

I have not been successful with this spf and I need some help if possible, please see the errors below:
C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  deasync.cc
  win_delay_load_hook.cc
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (
compiling source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\v8.h(3243): note: see declaration of 'v8::Object' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(834): warning C4996: 'node::MakeCallback': was declared deprecated (compiling
 source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(849): warning C4996: 'node::MakeCallback': was declared deprecated (compiling
 source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(864): warning C4996: 'node::MakeCallback': was declared deprecated (compiling
 source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
c:\projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\node_modules\nan\nan.h(1473): warning C4996: 'node::MakeCallback': was declared deprecated (compilin
g source file ..\src\deasync.cc) [C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync\build\deasync.vcxproj]
  c:\users\xxx\.node-gyp\10.15.3\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\deasync.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projects\sp-dev-fx-extensions\samples\react-application-tenant-global-navbar\node_modules\deasync
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):les\fsevents):                                                           events@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.10 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!

**Comment by MichaelDell** [comment]
Work around...

Replace all hrefs in ContextualMenuItems with onclick event.

                    //href:item.Url,
                    onClick: () => { event.preventDefault(); window.location.href = item.Url; },

**Comment by hugoabernier** [comment]
@clohigh did you ever resolve this issue with @MichaelDell 's suggestion?

I'll go ahead and close it as there has been no activity here for a while. If you're still experiencing issues, feel free to open a new issue.

Thanks @MichaelDell for your help with this one.
