### ISSUE TITLE
ReferenceError: Primordials is not defined

### ISSUE THREAD

**Issue by 88naveen** [pnp/sp-dev-fx-extensions#413]
### Sample

https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/jquery-application-toastr

### Author(s)

@

### Question

I am getting this error  and not sure how to proceed if someone can educate me that would be a great help

Using these config
node -v
v14.17.3
npm -v
6.14.13

 @microsoft/generator-sharepoint@1.12.1

PS C:\DemoDev\jquery-application-toastr> gulp serve
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (C:\DemoDev\jquery-application-toastr\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\DemoDev\jquery-application-toastr\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\DemoDev\jquery-application-toastr\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)

**Comment by notariorob** [comment]
Hi @88naveen, switching to node v11 or v10 should solve the issue. You can use nvm to switch between node versions easily.
